version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - "8080:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api

  server:
    build:
      context: ./server
    ports:
      - "5001:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=creator
      - DB_PASSWORD=password
      - DB_NAME=creator_center
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=creator_center
      - MYSQL_USER=creator
      - MYSQL_PASSWORD=password 